cicd updated

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -42,7 +42,7 @@ jobs:
 
   Continuous-Deployment:
     needs: Continuous-Integration
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
     steps:
 
       - name: Checkout
@@ -70,13 +70,17 @@ jobs:
       - name: Run Docker Image to serve users
         run: |
           docker run -d \
-          -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID}}" \
-          -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
-          -e AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}" \
-          -e PINECONE_API_KEY="${{ secrets.PINECONE_API_KEY}}" \
-          -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
-          -p 8080:8080 \
-          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest
+            --name medical-chatbot \
+            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
+            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
+            -e AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}" \
+            -e PINECONE_API_KEY="${{ secrets.PINECONE_API_KEY }}" \
+            -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
+            -p 8080:8080 \
+            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest
+
+          echo "🔍 Container logs:"
+          sleep 5 && docker logs medical-chatbot || echo "❌ Failed to start container"
 
 
 
